### ISSUE TITLE
Is it ok to checkout commit to test bipedalwalker?

### ISSUE THREAD

**Issue by Coelancanth** [JunhongXu/ppo-pytorch#1]
Hi, just wondering if I want to test bipedalwalker, is it OK to fcheckout commit de909e7b18a219c80618fbd034d58b69ac3a4346 (play bipedalwalker! committed on 26 Nov 2017). 

after 1500 episodes trainging ( episodes length is 2048), my test result is is still very unsatisfactory, sometimes printed rewards could be -1000 or worse. performed very bad comparing with your video. 

Thanks in advance...

**Comment by JunhongXu** [comment]
Hi,

Thanks for using reporting the issue. I have updated ppo_gym.py to play Bipedalwalker successfully. The reason of the policy not performing very well might because that the coeff_entropy is too high and the policy just learns random actions.

**Comment by Coelancanth** [comment]
Hi, 

it worked! 

BTW, this is the clearest ppo implementation I  found by far on github. 

Thanks again!

**Comment by JunhongXu** [comment]
You are welcome. Glad this works. You can also see OpenAI Baselines: https://github.com/openai/baselines

Close the issue.
